### ISSUE TITLE
Recommender startup is not resilient enough

### ISSUE THREAD

**Issue by SimonEismann** [DescartesResearch/TeaStore#110]
Sometimes, the recommender fails to start with the following message:

[pool-3-thread-1] INFO com.netflix.loadbalancer.BaseLoadBalancer - Client: default instantiated a LoadBalancer: {NFLoadBalancer:name=default,current list of Servers=[],Load balancer stats=Zone stats: {},Server stats: []}
java.lang.NullPointerException: ServiceLoadBalancerResult was null!
	at tools.descartes.teastore.registryclient.loadbalancers.ServiceLoadBalancer.loadBalanceRESTOperation(ServiceLoadBalancer.java:229)
	at tools.descartes.teastore.registryclient.loadbalancers.ServiceLoadBalancer.loadBalanceRESTOperation(ServiceLoadBalancer.java:201)
	at tools.descartes.teastore.recommender.servlet.TrainingSynchronizer.waitForPersistence(TrainingSynchronizer.java:138)
	at tools.descartes.teastore.recommender.servlet.TrainingSynchronizer.retrieveDataAndRetrain(TrainingSynchronizer.java:178)
	at tools.descartes.teastore.recommender.servlet.RecommenderStartup.lambda$contextInitialized$0(RecommenderStartup.java:71)
	at tools.descartes.teastore.registryclient.StartupCallbackTask.run(StartupCallbackTask.java:59)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by jo102tz** [comment]
This issue should be fixed in the new version.

**Comment by SimonEismann** [comment]
This is unfortunately not fixed yet, in order to reproduce, create a docker-compose fill containing all services

**Comment by SimonEismann** [comment]
Could not reproduce
